apiVersion: v1
kind: Pod
metadata:
  name: tolerated-pod
  namespace: tolerations-lab
spec:
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "database"
    effect: "NoSchedule"
  containers:
  - name: database
    image: redis:alpine
