apiVersion: v1
kind: Pod
metadata:
  name: burstable-pod
  namespace: resource-lab
spec:
  containers:
  - name: web
    image: nginx:alpine
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
