apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: project-3
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-reader
  namespace: project-3
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-configs
  namespace: project-3
subjects:
  - kind: ServiceAccount
    name: wrong-sa
    namespace: project-3
roleRef:
  kind: Role
  name: config-reader
  apiGroup: rbac.authorization.k8s.io
