apiVersion: v1
kind: Pod
metadata:
  name: standard-pod
  namespace: debugging-lab
spec:
  containers:
    - name: app
      image: alpine:3.18
      command: ["sh", "-c", "while true; do echo 'App running'; sleep 10; done"]
