apiVersion: v1
kind: LimitRange
metadata:
  name: project-limits
  namespace: phase1-project
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    max:
      cpu: "1"
      memory: "1.5Gi"
    min:
      cpu: "50m"
      memory: "64Mi"
