apiVersion: v1
kind: ResourceQuota
metadata:
  name: project-quota
  namespace: phase1-project
spec:
  hard:
    pods: "4"
    requests.cpu: "1.5"
    requests.memory: "1.5Gi"
    limits.cpu: "3"
    limits.memory: "3Gi"
