apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinity-pod
  namespace: scheduling-lab
  labels:
    app: affinity-test
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
            operator: In
            values:
            - us-east-1a
            - us-east-1b
  containers:
  - name: web
    image: nginx:alpine
