apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  namespace: scheduling-lab
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - database
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: client
    image: alpine:latest
    command: ["sleep", "3600"]
